Jean's branch
pedroishida/project0 pull request #2
Opened 2019-07-29 17:15 UTC by matheuslazarotto

print_jean() function added to ''custom_printer.cpp'' and ''custom_printer.hpp''

2019-07-30 23:46 UTC, pedroishida requested changes
Resolver os conflitos.

2019-07-31 19:22 UTC, pedroishida commented
Está tudo certo. Agora é só esperar as aprovações e fazer o merge.

2019-07-31 19:23 UTC, pedroishida approved these changes

2019-08-01 02:15 UTC, geovanegrossi approved these changes
Accepted

2019-08-09 18:44 UTC, m-palmero commented on custom_printer.cpp
> +  printers.push_back(print_geovane);
TAB!

2019-08-09 18:47 UTC, m-palmero approved these changes

2019-08-09 18:47 UTC, merged