Added branch Giu and print_geovane()
pedroishida/project0 pull request #3
Opened 2019-07-31 00:45 UTC by geovanegrossi

print_geovane() function added to ''custom_printer.cpp'' and ''custom_printer.hpp''

2019-07-31 01:42 UTC, pedroishida requested changes

2019-07-31 01:42 UTC, pedroishida commented on custom_printer.cpp
> +
Apagar essa linha extra.

2019-07-31 01:42 UTC, pedroishida commented on custom_printer.cpp
> +
Apagar essa linha extra.

2019-07-31 01:42 UTC, pedroishida commented on custom_printer.hpp
> +
Apagar linha extra.

2019-08-01 02:16 UTC, geovanegrossi commented on custom_printer.hpp
> +
Oi Pedro, fiz as alterações via terminal. Depois da uma olhada se está tudo certo

2019-08-01 03:45 UTC, pedroishida requested changes

2019-08-01 03:45 UTC, pedroishida commented on custom_printer.cpp
> +
Então... Sobrou uma. xD

2019-08-01 04:50 UTC, geovanegrossi reviewed
Acho que foi.

2019-08-01 14:05 UTC, matheuslazarotto approved these changes
Approved

2019-08-01 20:06 UTC, pedroishida approved these changes

2019-08-08 23:45 UTC, vitor-de-oliveira approved these changes
Go for it

2019-08-09 14:07 UTC, merged