Created function print_vitor and corrected README file
pedroishida/project0 pull request #7
Opened 2019-08-10 20:51 UTC by vitor-de-oliveira

Lets do this

2019-08-10 21:38 UTC, pedroishida requested changes

2019-08-10 21:38 UTC, pedroishida commented on custom_printer.cpp
> +	cout << "This is 007 speaking. This is an open line. It's an emergency. Can you hear me? Pass this at once. 3030 was a double, working for Redland. Yes, dammit, I said was. The bitch is dead now." <
Para não ter uma linha com mais de 80 colunas, você pode fazer uma separação deste tipo:
```c
cout << "This is 007 speaking. This is an open line. It's an emergency.";
cout << "Can you hear me? Pass this at once.";
cout << "3030 was a double, working for Redland.";
cout << "Yes, dammit, I said was. The bitch is dead now." << endl;
```
Sem `endl` ou `"\n"`, o cout não pulará linha.

2019-08-14 16:23 UTC, vitor-de-oliveira commented on custom_printer.cpp
> +	cout << "This is 007 speaking. This is an open line. It's an emergency. Can you hear me? Pass this at once. 3030 was a double, working for Redland. Yes, dammit, I said was. The bitch is dead now." <
Beleza!

2019-08-14 19:12 UTC, pedroishida approved these changes

2019-08-15 15:11 UTC, geovanegrossi approved these changes
Approved

2019-08-16 17:43 UTC, m-palmero approved these changes
Boa

2019-08-16 17:43 UTC, merged